import { DonationStatus, FoodType } from "@/@types";
import { DonationWithUIDetails } from "../typeDonation";

export  const mockData: DonationWithUIDetails[] = [
          {
            id: "1",
            donorId: "donor1" as any,
            title: "Fresh Vegetables Assortment",
            description:
              "Mix of freshly harvested vegetables: carrots, lettuce, tomatoes, and peppers",
            quantity: 15,
            foodType: FoodType.Vegetables,
            pickupDeadline: new Date(Date.now() + 1000 * 60 * 60 * 24),
            pickupInstruction: "Come to the back entrance of the store",
            location: {
              lat: 40.7128,
              lng: -74.006,
            },
            status: DonationStatus.Available,
            imageUrl: "/api/placeholder/300/200",
            donorName: "Local Farm Market",
            createdAt: new Date(Date.now() - 1000 * 60 * 60 * 3),
          },
          {
            id: "2",
            donorId: "donor2" as any,
            title: "Bread and Pastries",
            description:
              "Assorted bread loaves and pastries from today's baking",
            quantity: 8,
            foodType: FoodType.GrainsCereals,
            pickupDeadline: new Date(Date.now() + 1000 * 60 * 60 * 12),
            pickupInstruction: "Ask for manager at front counter",
            location: {
              lat: 40.7328,
              lng: -73.986,
            },
            status: DonationStatus.Available,
            imageUrl: "/api/placeholder/300/200",
            donorName: "Fresh Bakery",
            createdAt: new Date(Date.now() - 1000 * 60 * 30),
          },
          {
            id: "3",
            donorId: "donor3" as any,
            title: "Dairy Products",
            description:
              "Milk, yogurt, and cheese approaching best-by date but still perfectly good",
            quantity: 12,
            foodType: FoodType.DairyAlternatives,
            pickupDeadline: new Date(Date.now() + 1000 * 60 * 60 * 8),
            pickupInstruction: "Please bring your own cooler bag if possible",
            location: {
              lat: 40.7428,
              lng: -74.026,
            },
            status: DonationStatus.Available,
            imageUrl: "/api/placeholder/300/200",
            donorName: "Family Grocery",
            createdAt: new Date(Date.now() - 1000 * 60 * 60 * 1),
          },
          {
            id: "4",
            donorId: "donor4" as any,
            title: "Canned Food Assortment",
            description:
              "Various non-perishable canned goods: beans, corn, soup",
            quantity: 25,
            foodType: FoodType.ProcessedFastFoods,
            pickupDeadline: new Date(Date.now() + 1000 * 60 * 60 * 48),
            pickupInstruction: "Community center front desk, ask for Jane",
            location: {
              lat: 40.7228,
              lng: -73.996,
            },
            status: DonationStatus.Claimed,
            imageUrl: "/api/placeholder/300/200",
            donorName: "Community Pantry",
            createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 2),
          },
          // Adding more mock data for pagination testing
          {
            id: "5",
            donorId: "donor5" as any,
            title: "Fresh Fruits Assortment",
            description: "Selection of fresh fruits including apples, bananas, and oranges",
            quantity: 20,
            foodType: FoodType.Fruits,
            pickupDeadline: new Date(Date.now() + 1000 * 60 * 60 * 36),
            pickupInstruction: "Ask for Mark at the service desk",
            location: {
              lat: 40.7228,
              lng: -73.996,
            },
            status: DonationStatus.Available,
            imageUrl: "/api/placeholder/300/200",
            donorName: "City Market",
            createdAt: new Date(Date.now() - 1000 * 60 * 60 * 12),
          },
          {
            id: "6",
            donorId: "donor6" as any,
            title: "Prepared Meals",
            description: "Pre-cooked meals from restaurant surplus",
            quantity: 10,
            foodType: FoodType.Beverages,
            pickupDeadline: new Date(Date.now() + 1000 * 60 * 60 * 4),
            pickupInstruction: "Side entrance, ring bell",
            location: {
              lat: 40.7528,
              lng: -73.976,
            },
            status: DonationStatus.Available,
            imageUrl: "/api/placeholder/300/200",
            donorName: "Riverside Restaurant",
            createdAt: new Date(Date.now() - 1000 * 60 * 60 * 5),
          },
          {
            id: "7",
            donorId: "donor7" as any,
            title: "Dry Beans and Rice",
            description: "Bulk dry goods perfect for food pantries",
            quantity: 50,
            foodType: FoodType.Fruits,
            pickupDeadline: new Date(Date.now() + 1000 * 60 * 60 * 72),
            pickupInstruction: "Loading dock at warehouse rear",
            location: {
              lat: 40.7328,
              lng: -74.016,
            },
            status: DonationStatus.Available,
            imageUrl: "/api/placeholder/300/200",
            donorName: "Wholesale Foods",
            createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 1),
          },
          {
            id: "8",
            donorId: "donor8" as any,
            title: "Baby Food and Formula",
            description: "Unexpired baby food jars and unopened formula",
            quantity: 15,
            foodType: FoodType.DairyAlternatives,
            pickupDeadline: new Date(Date.now() + 1000 * 60 * 60 * 48),
            pickupInstruction: "Front desk of family center",
            location: {
              lat: 40.7628,
              lng: -73.956,
            },
            status: DonationStatus.Available,
            imageUrl: "/api/placeholder/300/200",
            donorName: "Family First Center",
            createdAt: new Date(Date.now() - 1000 * 60 * 60 * 10),
          },
        ];